title:             Laniakea
email:             your-email@example.com
description:       Automatic deployment of virtual Galaxy environments for life science
author:            Start Bootstrap
baseurl:           "/"
url:               "http://elixir-italy-laniakea.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
