title:             LANIAKEA
logo:              "https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/elixir_italy_white_background.png"
navbar_title:      ELIXIR Italy Laniakea
navbar_logo:       "https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/ELIXIR_ITALY_orange.png"
email:             ma.tangaro@ibiom.cnr.it
description:       Automatic deployment of virtual Galaxy environments for life science
author:            Marco Tangaro
baseurl:           "/"
url:               "http://laniakea-elixir-it.github.io"

# Navbar links
navigation:
  - {name: 'Home', link: '/'}
  - {name: 'News', link: '/posts'}
  - {name: 'Documentation', link: 'https://laniakea.readthedocs.io/en/latest/'}
  - {name: 'Deploy', link: 'https://cloud-90-147-170-32.cloud.ba.infn.it'}
  #- {name: 'Deploy', link: 'https://laniakea-elixir-it.github.io/2019/06/11/beta-program-end.html'}
  - {name: 'About', link: '/about'}
  - {name: 'Contacts', link: '/contact'}

# Contributors
contributors:
- {name: 'elixir-italy', logo_link: 'https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/elixir_italy_white_background.png'}
- {name: 'ibiom-cnr', logo_link: 'https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/IBIOM.png'}
- {name: 'infn-bari', logo_link: 'https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/INFN.png'}
- {name: 'unimi', logo_link: 'https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/UNIMI.jpg'}
- {name: 'recas-bari', logo_link: 'https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/ReCaS.png'}


# Social Profiles
github_username:   Laniakea-elixir-it
twitter_username:  elixir_it
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
