title:             Laniakea
logo:              "https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/elixir_italy_white_background.png"
navbar_title:      Elixir-Italy Laniakea
navbar_logo:       "https://raw.githubusercontent.com/Laniakea-elixir-it/resources/master/logos/elixir-white-orange-logo.png"
email:             ma.tangaro@ibiom.cnr.it
description:       Automatic deployment of virtual Galaxy environments for life science
author:            Start Bootstrap
baseurl:           "/elixir-italy-laniakea"
url:               "http://mtangaro.github.io"

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'News', link: '/posts'}
  - {name: 'Documentation', link: 'https://laniakea.readthedocs.io/en/latest/'}
  - {name: 'Deploy', link: 'https://cloud-90-147-75-117.cloud.ba.infn.it/login'}
  - {name: 'About', link: '/about'}
  - {name: 'Contacts', link: '/contact'}

# Social Profiles
github_username:   Laniakea-elixir-it
twitter_username:  elixir_ita
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
